---
title: "Compra de Pneus"
author: "Ramon Roldan"
date: "2023-01-30"
categories: [Data Science, Tydeverse]
tags: [Machine Learning, Tydeverse, Analitycs, Dashboard, Data Science, ETL]
---

## Principal Objetivo

Este estudo busca utilizar técnicas de Data Science para sugerir a melhor opção de compra de pneus conforme produtos atualmente disponíveis no mercado de varejo.

## Motivação do Estudo

Recentemente tive a felicidade de comprar meu primeiro carro, um lindo Ford Ka branco modelo 2017, mas como todo carro de segunda mão sempre precisamos arrumar alguma coisa.

Orientado para cultura de Data Driven, e muita experiencia na área de suprimentos, decidi realizar uma pesquisa de mercado.

## Organização do Trabalho

Premissas: Este trabalho foi realizado com a linguagem R, IDE Rstudio, com Quarto, e sistema operacional Linux Mint. Foram utilizados conhecimentos de data science e metodologias ágeis. Seguindo as boas práticas do mercado demos preferencia para bibliotecas do tidyverse.

Principais Etapas:

-   Definição do objetivo do trabalho;

-   Versionar trabalho no GitHub;

-   Utilizar a ferramenta Kanban para organizar projeto no formato de metodologia ágil;

-   Coleta dos dados;

-   Realizar analise exploratória;

-   Limpeza e tratamento dos dados;

-   Salvar modelo treinado em arquivo r para posteriormente aplicar no framework tidymodels;

-   Desenvolver um dashboard dinâmico com os pacotes flexdashboard, shiny e ploty;

-   Realizar deploy do modelo and uploud in the shinyapp.io

## Versionar trabalho no GitHub 

\

```{r}
library(tidyverse)
library(rvest)

url <- 'https://www.pneustore.com.br/categorias/pneus-de-carro/pneus-175-65r14/produto/pneu-firestone-aro-14-f-600-175-65r14-82t-10100082'

base <- read_html(url) %>%
  html_node("table") %>%
  html_table() %>%
  as_tibble() 

base %>% rename('variavel'='X1','resultado'='X2')

```
